# Generated by Django 3.2.4 on 2022-02-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20220123_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
    ]
