# Generated by Django 3.2.4 on 2022-02-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_remove_artwork_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_ref',
        ),
    ]
