# Generated by Django 3.2.4 on 2022-02-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_remove_artwork_image_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='catalog_id',
        ),
    ]
