# Generated by Django 3.2.4 on 2022-02-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_remove_artwork_catalog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='pub_date',
        ),
    ]
